deitch/docker_registry2

README.md
docker_registry2.gemspec
lib/docker_registry2.rb
lib/registry/exceptions.rb
lib/registry/registry.rb
lib/registry/version.rb

This commit introduces means to avoid name collision
between this gem and docker_registry gem used for
v1 docker registries and index.docker.io.
Both gems introduce class DockerRegistry::Registry which
makes it impossible to use both of them in one program.
This commit renames module DockerRegistry to DockerRegistry2
and moves its definition from docker_registry2.rb to
docker_registry2_ex.rb. In addition this commit introduces
alias DockerRegistry for DockerRegistry2 in file
docker_registry2.rb.
This way, old code benefits from backward compatibility
by requiring docker_registry2.rb and new code can
avoid name collision by requiring docker_registry2_ex.rb.
This patch except new docker_registry2.rb was generated by:
git mv lib/docker_registry2.rb lib/docker_registry2_ex.rb
sed -i …

Fix name collision with docker_registry gem

---

README.md
lib/docker_registry2.rb
lib/registry/version.rb

When no registry is supplied to `DockerRegistry2.connect()`, default to the global https://registry.hub.docker.com

Add default registry

---

.gitignore
CHANGELOG.md
lib/docker_registry2.rb
lib/registry/registry.rb
lib/registry/version.rb

Hey @deitch,
Thanks for this gem! It works a treat, and as far as I can tell is still the only client for the registry API.
I've moved the `ping` method out of the `DockerRegistry2::Registry` initialize method and into the `DockerRegistry2.connect` method, because it saves a request for anyone creating a `DockerRegistry2::Registry` instance by hand (and I don't want to spam the registry with unnecessary pings).

Move ping out of initialize method

---

CHANGELOG.md
README.md
lib/registry/registry.rb
lib/registry/version.rb

By default, `RestClient` will wait up to 60 seconds to open a connection with a registry. That's a bit long - this PR reduces the time we're willing to wait for a connection to 2 seconds, and the time we're willing to wait for data to 5. Both should be well within normal parameters for a registry, right?

Add sensible timeouts

---

Gemfile

This is standard practice for Ruby gems. Means all the declarations are in the gemspec, rather than split between the Gemfile and the gemspec.
(Doesn't need a release - just makes development easier.)

Import gemspec into Gemfile (so gem declarations are all in a single place)

---

lib/registry/exceptions.rb
lib/registry/registry.rb
lib/registry/version.rb

It's useful for me to catch RestClient::NotFound exceptions here, so probably useful for others too ;)

New DockerRegistry2::NotFound exceptions

---

CHANGELOG.md
lib/registry/registry.rb
lib/registry/version.rb

Currently only used in `do_bearer_req`. Should be used in `do_basic_req`, too.
Still loving this library - we use it in Dependabot to help with all our automated Dockerfile updates. :octocat:

Use DockerRegistry2::NotFound consistently

---

CHANGELOG.md
lib/registry/registry.rb
lib/registry/version.rb

I am an idiot and should have done this in 1.3.2. Sorry! This does now cover all places requests are made.

Use DockerRegistry2::NotFound in unauthenticated request calls

---

lib/registry/registry.rb
lib/registry/version.rb

Some private registries return 403s when attempting to authenticate without credentials. We should handle this is exactly the same way as 401s.

Handle 403s when authenticating

---

lib/registry/registry.rb

Hi. I'm trying docker_registry2 with Azure ACR but authentication has been failed because ACR returns token into access_token field instead of token field. (See https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token-for-helm-repository)
There is no standard spec for naming but both of names are used frequently, so I've added fallback.

Support OAuth providers that issue token via access_token field

---

docker_registry2.gemspec
lib/registry/version.rb

They are unnecessary, and can cause issues on Windows.
Signed-off-by: Tom Duffield <tom@chef.io>

Do not ship test fixtures with gem

---

README.md
lib/registry/registry.rb
lib/registry/version.rb

Resolves the [comment here](https://github.com/deitch/docker_registry2/pull/35#issuecomment-506527834) by @dzunk about the pagination handling breaking backwards compatibility.

backwards-compatible default for pagination

---

CHANGELOG.md
lib/registry/registry.rb
lib/registry/version.rb

Add `application/json` to the list of acceptable response formats from registries to fix Artifactory returning 406 Not Acceptable errors when application/vnd.docker.distribution.manifest.v2+json is requested on the tags endpoint.

Accept application/json (fixes Not Acceptable errors from Artifactory)

---

lib/registry/registry.rb

The variable response is assigned but not used which causes a warning when running minitest: 'warning: assigned but unused variable - response'

Remove unused assignment to suppress warning

---

README.md
lib/registry/registry.rb

It’s not a new feature so much as a generalization of the way we configure the timeouts. This allows users to configure TLS options and proxies on a per-registry basis.
I considered passing any unknown option keyword through to RestClient, but given Registry has special options, I thought we’d better not mix HTTP-related options and Registry-related options together.
Though I wouldn’t specifically encourage overriding RestClient’s timeouts, I chose to keep a full compatiblity with the existing implementation.

Support passing options for RestClient

---

lib/docker_registry2.rb
lib/registry/registry.rb

With the following code, I was getting auth issues, despite this being a public repository.
```
reg = DockerRegistry2.connect("https://us.gcr.io")
pp reg.tags("k8s-artifacts-prod/autoscaling/cluster-autoscaler")
```
The scope wasn't being set due to `ping` not having the request context; removing it entirely fixed it for my use case. Although the tests pass, I do not know for certain if this has negative side effects for other use cases.

Remove ping so that proper scope is used.

---

lib/registry/registry.rb

If the headers that come back from the registry don't have `www_authenticate` present, as mine didn't, you get 
```
undefined method 'downcase' for nil:NilClass
```
My response didn't have the authenticate key:
```
e.response.headers
=> {:content_type=>"application/json", :docker_distribution_api_version=>"registry/2.0", :date=>"Fri, 24 Jun 2022 18:12:58 GMT", :content_length=>"73", :strict_transport_security=>"max-age=31536000", :docker_ratelimit_source=>"71.232.50.20"}
```
Which blows up on this line:
[e.response.headers[:www_authenticate].downcase.split(' ')[0]
](https://github.com/deitch/docker_registry2/blob/master/lib/registry/registry.rb#L260)
Since .to_s on a nil is '', this tiny PR makes the rest of the logic work when the header is missing.
I had trouble getting the test suite …

Fix undefined method error when www_authenticate header is nil

---

lib/registry/registry.rb

quay.io does something nonstandard with pagination. This is a workaround until https://issues.redhat.com/browse/PROJQUAY-498 is addressed.

fixes #56 quay.io nonstandard tag pagination

---

.github/workflows/spec.yml
.gitignore
.rspec
.rubocop.yml
docker_registry2.gemspec
spec/docker_registry2_spec.rb
spec/spec_helper.rb
spec/vcr/manifest/hello-world-v1_latest.yml
spec/vcr/manifest/hello-world-v1_non_existent.yml
spec/vcr/manifest/hello-world-v99_latest.yml
spec/vcr/tags/hello-world-v1.yml
spec/vcr/tags/hello-world-v99.yml

In this PR I'm adding the specs for the class methods (`.manifest`, `.tags`), following the tests that we have on `test/test.rb`
Note that I'm using [VCR](https://github.com/vcr/vcr) to avoid hitting the registry while running the specs

Add initial specs for the class methods

---

lib/registry/registry.rb

Avoid a stack trace when a nonexistent private image is encountered.

Add useful error message for DockerRegistry2::NotFound

---

lib/registry/registry.rb

Image registries that conform to the standard such as the reference [distribution/distribution](https://github.com/distribution/distribution) require the relevant `application/vnd.oci.image.*` `Accept` headers to be set in order to serve the images.

Support OCI images

---

lib/registry/registry.rb

registry.access.redhat.com behaves the same way as quay.io.
Need this fix for Dependabot to be able to page through responses of repositories on registry.access.redhat.com.
See https://github.com/dependabot/dependabot-core/issues/7562

Fix pagination for registry.access.redhat.com

---

.rubocop.yml
lib/registry/registry.rb
spec/docker_registry2_spec.rb
spec/vcr/search/hello_world.yml

When paginating, some registries return an absolute URL in the Link HTTP header. This happened on Amazon ECR, and docker_registry2 generated a bad URI exception when trying to request `https://….com:443https://…`. The absolute URL was naively appended to the base URL.
URI.join provides a smarter way to concatenate URLs, and behaves pretty much like `<a href="…">` would in an HTML document. To preserve the path of the base URL, I forced a trailing slash and made the API paths relative. Otherwise, the semantic of `/v2` is to go back to the root.
It looks like the Rubocop configuration in the CI is outdated, causing a failure.

Smartly join URLs

---

lib/registry/registry.rb

close #106 
Remove special cases for quay.io & registry.access.redhat.com: they were added by #63 and #92, but don't seem necessary anymore:
```
$ curl -Is https://quay.io/v2/keycloak/keycloak/tags/list | grep -i link
link: </v2/keycloak/keycloak/tags/list?n=100&last=23.0.4-0>; rel="next"
```
```
$ curl -Is https://registry.access.redhat.com:443/v2/ubi8/ubi-minimal/tags/list | grep -i link
Link: </v2/ubi8/ubi-minimal/tags/list?n=100&last=8.7-1031-source>; rel="next"
```

Fix pagination for tags list pagination for quay.io & registry.access.redhat.com registries
